# Generated by Django 4.2 on 2023-04-04 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_account_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('daily_usage', models.IntegerField(default=0)),
                ('usage_reset_date', models.DateTimeField()),
                ('is_subscribed', models.BooleanField(default=False)),
                ('joined_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
