# Generated by Django 4.2 on 2023-05-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
