# Generated by Django 4.2 on 2024-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extension_api', '0002_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('original_text', models.TextField()),
                ('summarized_text', models.TextField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
