# Generated by Django 4.2 on 2024-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension_api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaries',
            name='model_used',
            field=models.CharField(blank=True, choices=[('gpt-4', 'Gpt-4')], max_length=20, null=True),
        ),
    ]
