# Generated by Django 4.2 on 2024-09-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extension_api', '0004_summaries_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaries',
            name='account_id',
            field=models.ForeignKey(default=106849511115687138225, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='google_account_id'),
            preserve_default=False,
        ),
    ]
