# Generated by Django 4.2 on 2024-09-19 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extension_api', '0005_summaries_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaries',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
